grafana:
  enabled: true
  grafana.ini:
    server:
      root_url: "http://a5c9bc89412fd4ae383aac6de65d3fc3-2e300aff05e97e0f.elb.us-east-1.amazonaws.com/grafana/" # Change ELB host to current host in all 6 places.
      serve_from_sub_path: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: ""  # <- REMOVE REWRITING ENTIRELY
    hosts:
      - a5c9bc89412fd4ae383aac6de65d3fc3-2e300aff05e97e0f.elb.us-east-1.amazonaws.com
    paths:
      - /grafana(/|$)(.*)
    pathType: Prefix

prometheus:
  prometheusSpec:
    externalUrl: "http://a5c9bc89412fd4ae383aac6de65d3fc3-2e300aff05e97e0f.elb.us-east-1.amazonaws.com/prometheus/"
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - a5c9bc89412fd4ae383aac6de65d3fc3-2e300aff05e97e0f.elb.us-east-1.amazonaws.com
    paths:
      - /prometheus(/|$)(.*)
    pathType: ImplementationSpecific

alertmanager:
  alertmanagerSpec:
    externalUrl: "http://a5c9bc89412fd4ae383aac6de65d3fc3-2e300aff05e97e0f.elb.us-east-1.amazonaws.com/alert/"
    alertmanagerConfigSelector:
      matchLabels:
        release: monitoring
    replicas: 2
    alertmanagerConfigMatcherStrategy:
      type: None
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - a5c9bc89412fd4ae383aac6de65d3fc3-2e300aff05e97e0f.elb.us-east-1.amazonaws.com
    paths:
      - /alert(/|$)(.*)
    pathType: ImplementationSpecific
